data:
  name: synthetic          # CIFAR100 or synthetic
  path: null
  batch_size: 256
  num_workers: 8
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true

model:
  name: resnet50           # torchvision model name
  num_classes: 1000
  channels_last: true

training:
  epochs: 3
  precision: amp           # fp32 | amp | bf16
  optimizer: SGD           # Adam | SGD
  learning_rate: 0.1
  weight_decay: 0.0
  momentum: 0.9
  grad_clip_norm: null
  compile:
    enabled: false
    mode: default
  seed: 1337
  cudnn_benchmark: true

benchmark:
  enabled: true
  warmup_steps: 100
  measure_by: steps        # steps | time
  measure_steps: 2000
  measure_seconds: null
  log_step_times: true
  sync_cuda: false
  evaluate_after: false

distributed:
  backend: nccl
  gradient_accumulation_steps: 1
  world_size: null
  local_rank: null
  node_rank: null

run:
  experiment_name: resnet50_synthetic_throughput
  run_id: null
  save_dir: ./results
  capture_env: true
  commit_hash: auto
  notes: "synthetic baseline"
